gh-588: Auto bump version

diff --git a/.travis.yml b/.travis.yml
--- a/.travis.yml
+++ b/.travis.yml
@@ -15,9 +15,39 @@ language: go
 install:  
   - curl -L https://codeclimate.com/downloads/test-reporter/test-reporter-latest-linux-amd64 > ./cc-test-reporter
   - chmod +x ./cc-test-reporter
+  - wget https://raw.githubusercontent.com/creativesoftwarefdn/semver-tool/master/src/semver
+  - chmod +x semver
 before_script:
   - sudo apt-get -qq -y update
-  - sudo apt-get -qq -y install jq coreutils
+  - sudo apt-get -qq -y install jq coreutils python
+  # Validate if the open-api schema needs to be bumped
+  - |
+    if [ $TRAVIS_PULL_REQUEST = "false" ]; then
+      WEAVIATESCHEMAFILE=openapi-specs/schema.json
+      PREVIOUSSEMVER=$(./semver compare $(git show --oneline HEAD:$WEAVIATESCHEMAFILE | jq -r ".info.version") $(git show --oneline HEAD~1:$WEAVIATESCHEMAFILE | jq -r ".info.version"))
+      if [ "$PREVIOUSSEMVER" -eq 0 ]; then
+        echo "Semver isn't bumped. Bumping as a PATCH"
+        # Bump the version and add to schema.json
+        NEWVERSIONJSON=$(jq -r '.info.version = $NEWVERSION' --arg NEWVERSION "$(semver bump patch $(git show --oneline HEAD:$WEAVIATESCHEMAFILE | jq -r ".info.version"))" $WEAVIATESCHEMAFILE)
+        echo $NEWVERSIONJSON > $WEAVIATESCHEMAFILE
+        # build with new version
+        ./tools/gen-code-from-swagger.sh
+        # push back to Git
+        git config --global user.email "travis@travis-ci.org"
+        git config --global user.name "Travis CI"
+        git add . $WEAVIATESCHEMAFILE
+        git commit --message "🤖 semver bump"
+        if ! git push --quiet --follow-tags "https://$GITHUB_TOKEN@github.com/$TRAVIS_REPO_SLUG" "$TRAVIS_BRANCH" > /dev/null 2>&1; then
+            err "failed to push git changes"
+            travis_terminate 1
+        fi
+        # exit will trigger a new build
+        travis_terminate 0
+      elif [ "$PREVIOUSSEMVER" -eq -1 ]; then
+        echo "Semver is behind the latest commit. This issue should be resolved and the version should be set to at least $(./semver bump patch $(git show --oneline HEAD~1:$SCHEMAFILE | jq -r ".info.version"))"
+        travis_terminate 1
+      fi
+    fi
   # Verify that the code is properly formatted.
   - if [[ -n "$(gofmt -l .)" ]]; then echo "The following files were not formatted properly!"; gofmt -l .; exit 1; fi
   # Run Weaviate backed by JanusGraph
