Better package name

diff --git a/.github/workflows/pull_requests.yaml b/.github/workflows/pull_requests.yaml
--- a/.github/workflows/pull_requests.yaml
+++ b/.github/workflows/pull_requests.yaml
@@ -9,125 +9,125 @@ on:
   pull_request:
 
 jobs:
-  Run-Swagger:
-    runs-on: ubuntu-latest
-    steps:
-      - uses: actions/checkout@v3
-      - name: Set up Go
-        uses: actions/setup-go@v3
-        with:
-          go-version: 1.19
-          cache: true
-      - name: Run Swagger
-        run: ./tools/gen-code-from-swagger.sh
-      - name: Error on change
-        run: |
-          # check if anything is different
-          CHANGED=$(git status -s | wc -l)
-          if [ "$CHANGED" -gt 0 ]; then
-            echo "Please run ./tools/gen-code-from-swagger.sh script and commit changes"
-            exit 1
-          else
-            exit 0
-          fi
-  Vulnerability-Scanning:
-    runs-on: ubuntu-latest
-    steps:
-      - uses: actions/checkout@v3
-      - name: Scan for Vulnerabilities in Code
-        uses: Templum/govulncheck-action@v0.0.8
-        with:
-          go-version: 1.19
-          vulncheck-version: latest
-          package: ./...
-          fail-on-vuln: true
-  Unit-Tests:
-    needs: [Run-Swagger]
-    runs-on: ubuntu-latest
-    steps:
-      - uses: actions/checkout@v3
-      - name: Set up Go
-        uses: actions/setup-go@v3
-        with:
-          go-version: 1.19
-          cache: true
-      - name: Unit test
-        run: ./test/run.sh --unit-only
-      - name: Codecov Unit
-        if: ${{ (github.ref_type == 'branch') && (github.ref_name != 'master') }}
-        uses: codecov/codecov-action@v3
-        with:
-          fail_ci_if_error: true
-          files: ./coverage-unit.txt
-          flags: unittests
-          verbose: true
-  Integration-Tests:
-    needs: [Run-Swagger]
-    runs-on: ubuntu-latest
-    steps:
-      - uses: actions/checkout@v3
-      - name: Set up Go
-        uses: actions/setup-go@v3
-        with:
-          go-version: 1.19
-          cache: true
-      - name: Integration test
-        run: ./test/run.sh --integration-only
-      - name: Codecov Integration
-        if: ${{ (github.ref_type == 'branch') && (github.ref_name != 'master') }}
-        uses: codecov/codecov-action@v3
-        with:
-          fail_ci_if_error: true
-          files: ./coverage-integration.txt
-          flags: integration
-          verbose: true
-  Modules-Acceptance-Tests:
-    needs: [Run-Swagger]
-    runs-on: ubuntu-latest-8-cores
-    steps:
-      - uses: actions/checkout@v3
-      - name: Set up Go
-        uses: actions/setup-go@v3
-        with:
-          go-version: 1.19
-          cache: true
-      - name: Acceptance tests (modules)
-        run: ./test/run.sh --acceptance-module-tests-only
-  Acceptance-Tests:
-    needs: [Run-Swagger]
-    runs-on: ubuntu-latest
-    steps:
-      - uses: actions/checkout@v3
-      - name: Set up Go
-        uses: actions/setup-go@v3
-        with:
-          go-version: 1.19
-          cache: true
-      - name: Acceptance tests (modules)
-        run: ./test/run.sh --acceptance-only
-  Push-Docker:
-    needs: [Acceptance-Tests, Modules-Acceptance-Tests, Unit-Tests, Integration-Tests, Vulnerability-Scanning]
-    runs-on: ubuntu-latest-8-cores
-    if: ${{ !github.event.pull_request.head.repo.fork }}  # no PRs from fork
-    steps:
-      - uses: actions/checkout@v3
-      - name: Login to Docker Hub
-        uses: docker/login-action@v2
-        with:
-          username: ${{secrets.DOCKER_USERNAME}}
-          password: ${{secrets.DOCKER_PASSWORD}}
-      - name: Push container
-        id: push-container
-        run: ./ci/push_docker.sh
-        env:
-          PR_TITLE: "${{ github.event.pull_request.title }}"
-      - name: Generate Report
-        env:
-          PREVIEW_TAG: "${{ steps.push-container.outputs.PREVIEW_TAG }}"
-        run: ./ci/generate_docker_report.sh
+#  Run-Swagger:
+#    runs-on: ubuntu-latest
+#    steps:
+#      - uses: actions/checkout@v3
+#      - name: Set up Go
+#        uses: actions/setup-go@v3
+#        with:
+#          go-version: 1.19
+#          cache: true
+#      - name: Run Swagger
+#        run: ./tools/gen-code-from-swagger.sh
+#      - name: Error on change
+#        run: |
+#          # check if anything is different
+#          CHANGED=$(git status -s | wc -l)
+#          if [ "$CHANGED" -gt 0 ]; then
+#            echo "Please run ./tools/gen-code-from-swagger.sh script and commit changes"
+#            exit 1
+#          else
+#            exit 0
+#          fi
+#  Vulnerability-Scanning:
+#    runs-on: ubuntu-latest
+#    steps:
+#      - uses: actions/checkout@v3
+#      - name: Scan for Vulnerabilities in Code
+#        uses: Templum/govulncheck-action@v0.0.8
+#        with:
+#          go-version: 1.19
+#          vulncheck-version: latest
+#          package: ./...
+#          fail-on-vuln: true
+#  Unit-Tests:
+#    needs: [Run-Swagger]
+#    runs-on: ubuntu-latest
+#    steps:
+#      - uses: actions/checkout@v3
+#      - name: Set up Go
+#        uses: actions/setup-go@v3
+#        with:
+#          go-version: 1.19
+#          cache: true
+#      - name: Unit test
+#        run: ./test/run.sh --unit-only
+#      - name: Codecov Unit
+#        if: ${{ (github.ref_type == 'branch') && (github.ref_name != 'master') }}
+#        uses: codecov/codecov-action@v3
+#        with:
+#          fail_ci_if_error: true
+#          files: ./coverage-unit.txt
+#          flags: unittests
+#          verbose: true
+#  Integration-Tests:
+#    needs: [Run-Swagger]
+#    runs-on: ubuntu-latest
+#    steps:
+#      - uses: actions/checkout@v3
+#      - name: Set up Go
+#        uses: actions/setup-go@v3
+#        with:
+#          go-version: 1.19
+#          cache: true
+#      - name: Integration test
+#        run: ./test/run.sh --integration-only
+#      - name: Codecov Integration
+#        if: ${{ (github.ref_type == 'branch') && (github.ref_name != 'master') }}
+#        uses: codecov/codecov-action@v3
+#        with:
+#          fail_ci_if_error: true
+#          files: ./coverage-integration.txt
+#          flags: integration
+#          verbose: true
+#  Modules-Acceptance-Tests:
+#    needs: [Run-Swagger]
+#    runs-on: ubuntu-latest-8-cores
+#    steps:
+#      - uses: actions/checkout@v3
+#      - name: Set up Go
+#        uses: actions/setup-go@v3
+#        with:
+#          go-version: 1.19
+#          cache: true
+#      - name: Acceptance tests (modules)
+#        run: ./test/run.sh --acceptance-module-tests-only
+#  Acceptance-Tests:
+#    needs: [Run-Swagger]
+#    runs-on: ubuntu-latest
+#    steps:
+#      - uses: actions/checkout@v3
+#      - name: Set up Go
+#        uses: actions/setup-go@v3
+#        with:
+#          go-version: 1.19
+#          cache: true
+#      - name: Acceptance tests (modules)
+#        run: ./test/run.sh --acceptance-only
+#  Push-Docker:
+#    needs: [Acceptance-Tests, Modules-Acceptance-Tests, Unit-Tests, Integration-Tests, Vulnerability-Scanning]
+#    runs-on: ubuntu-latest-8-cores
+#    if: ${{ !github.event.pull_request.head.repo.fork }}  # no PRs from fork
+#    steps:
+#      - uses: actions/checkout@v3
+#      - name: Login to Docker Hub
+#        uses: docker/login-action@v2
+#        with:
+#          username: ${{secrets.DOCKER_USERNAME}}
+#          password: ${{secrets.DOCKER_PASSWORD}}
+#      - name: Push container
+#        id: push-container
+#        run: ./ci/push_docker.sh
+#        env:
+#          PR_TITLE: "${{ github.event.pull_request.title }}"
+#      - name: Generate Report
+#        env:
+#          PREVIEW_TAG: "${{ steps.push-container.outputs.PREVIEW_TAG }}"
+#        run: ./ci/generate_docker_report.sh
 
   Push-Registry:
-    needs: [Acceptance-Tests, Modules-Acceptance-Tests, Unit-Tests, Integration-Tests, Vulnerability-Scanning]
+#    needs: [Acceptance-Tests, Modules-Acceptance-Tests, Unit-Tests, Integration-Tests, Vulnerability-Scanning]
     runs-on: ubuntu-latest-8-cores
     if: ${{ !github.event.pull_request.head.repo.fork }}  # no PRs from fork
     permissions:
@@ -137,24 +137,10 @@ jobs:
       IMAGE_NAME: weaviate
     steps:
       - uses: actions/checkout@v3
-      - name: Build image
-        run: docker build . --file Dockerfile --tag $IMAGE_NAME
       - name: Log in to registry
         run: echo "${{ secrets.GITHUB_TOKEN }}" | docker login ghcr.io -u $ --password-stdin
-
       - name: Push image
-        run: |
-          IMAGE_ID=ghcr.io/${{ github.repository_owner }}/$IMAGE_NAME
-
-          # Change all uppercase to lowercase
-          IMAGE_ID=$(echo $IMAGE_ID | tr '[A-Z]' '[a-z]')
-          # Strip git ref prefix from version
-          VERSION=$(echo "${{ github.ref }}" | sed -e 's,.*/\(.*\),\1,')
-          # Strip "v" prefix from tag name
-          [[ "${{ github.ref }}" == "refs/tags/"* ]] && VERSION=$(echo $VERSION | sed -e 's/^v//')
-          # Use Docker `latest` tag convention
-          [ "$VERSION" == "master" ] && VERSION=latest
-          echo IMAGE_ID=$IMAGE_ID
-          echo VERSION=$VERSION
-          docker tag $IMAGE_NAME $IMAGE_ID:$VERSION
-          docker push $IMAGE_ID:$VERSION
+        env:
+          PR_TITLE: "${{ github.event.pull_request.title }}"
+          REPO_OWNER: "${{ github.repository_owner }}"
+        run: ./ci/push_registry.sh
